### ISSUE TITLE
Clearer documentation around participant/session IDs

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/documentation#182]
### Description

With the introduction of support for session-level data, there are some restrictions and quirks concerning how participant & session IDs are treated by Neurobagel, which are not well documented but can trip up first time users.

Somewhere in the docs for the data preparation or annotation stages, we should explicitly mention the following:
- Missing values are not allowed in columns annotated as being about participant or session IDs. This is important for TSVs with multiple columns containing participant/session identifier info.
- Neurobagel currently only supports one column annotation for participant ID and session ID (but you can have other columns in your TSV with different IDs, Neurobagel will just ignore them)
- Session IDs, unlike subject IDs, **do not** need to be the same across the BIDS directory and the phenotypic TSV (because pheno and BIDS sessions are treated as separate)

### Relevant documentation pages

- https://neurobagel.org/data_prep/#general-requirements-for-the-phenotypic-tsv
- http://neurobagel.org/dictionaries/#phenotypic-attributes

## TODO

- [x] Add warning / note that NAs are not allowed for pariticipant/session columns here: https://neurobagel.org/data_prep/#general-requirements-for-the-phenotypic-tsv
- [x] Add a note here https://neurobagel.org/data_prep/#multiple-participant-or-session-identifier-columns that we currently only allow a single column to be "about" participant and session each
- [x] Add a note that session IDs in tabular data do not have to use the same session IDs as BIDS, but they can
