### ISSUE TITLE
feedback after doing sysadmin install w/o stardog

### ISSUE THREAD

**Issue by thomasbeaudry** [neurobagel/documentation#67]
- [x] #142 

- [x] #141

- [x] Pick a better heading than "Changes to config files".  Maybe  "Configure the environment file".  

- [x] FOR:  The below steps are distilled from these instructions
>> Is there a reason to post these insturctions? I would avoid too many links since you want the user to have all the info they need for an install on the same page, and not have to consult serveral sources if something goes wrong.  Also for the non-stardog install, you need to have all the instructions on 1 page, and not have me refer to the stardog install page to avoid confusion  (for instance DBNAME is my_db/query  vs just my_db)

- [x] ~I would colour code the first 4 lines of the .env file table that you strongly suggest that users set~

- [x] #140

- [x] ~Don't make the template a '.' file.  It's easy to miss~

- [x] ~In .template-env file have the first 4 lines be the settings you want people to always configure.  Also for the following:~

NB_GRAPH_USERNAME=DBUSER  # REPLACE DBUSER WITH YOUR GRAPH DATABASE USERNAME
NB_GRAPH_PASSWORD=DBPASSWORD  # REPLACE DBPASSWORD WITH YOUR GRAPH DATABASE PASSWORD

I would change the comments to be:  REPLACE DBUSER WITH A GRAPH DATABASE USERNAME YOU WANT TO CREATE  and REPLACE DBPASSWORD WITH A GRAPH DATABASE PASSWORD FOR THE DBUSER.   This avoids confusion for the admin thinking that they had to create the user and set the password before editing this file.  Not everyone will read all the steps on your install doc, before starting them.

- [x] remove this command:   export $(cat .env | xargs)  from (https://neurobagel.org/infrastructure/#launch-the-api-and-graph-stack)

- [x] ~change command:  docker compose up -d    to:    sudo docker-compose up -d~

- [x] Replace:  Now we can create a user for the API:    with   Now we can create a user for the API using the same values you set in the .env file:

- [x] curl -X POST --header 'Content-Type: application/json' -d true http://localhost:7200/rest/security
is missing the '  at the end of the curl command

- [x] In graphDB, graph databases are called resources. To create a new one, you will also have to prepare a data-config.ttl file that contains the settings for the resource you will create (see the graphDB docs).

>> What am I looking at the graphDB docs for?  Should it be  (for more info see the graphDB docs),  or should it be (for advanced configurations see the graphDB docs), etc?

- [x] After:

curl -X PUT --header 'Content-Type: application/json' -d '
{"grantedAuthorities": ["WRITE_REPO_my_db","READ_REPO_my_db"]}'  http://localhost:7200/rest/security/users/DBUSER -u "admin:newpassword"

Change the next 2 lines to:

where:
"WRITE_REPO_my_db": grants write permission
"READ_REPO_my_db": grants read permission

**Comment by alyssadai** [comment]
Thanks for the detailed feedback @thomasbeaudry!

I've turned your suggestions into checkboxes so we can track which ones we've implemented.

**Comment by surchs** [comment]
@surchs please move

**Comment by surchs** [comment]
when active, we discuss it and then decide what to do with each point

**Comment by surchs** [comment]
Things to implement / turn into issues: 

- Add a first step (step 0) / or a heading to install dependencies: docker, docker-compose, plus whatever else you need. This should always be at the start of an installation page (normally under a brief intro of what you are about to install).
- Add numbers to each step. i.e. 1. get a license 2. Launch the api stack (for the public docs as well as this one). I suggest this because, the heading "Launch the API stack" can be a bit confusing to users, since they want to install it, and aren't thinking of "API" yet
- Whenever you mention API container, i would refer to it as the Neurobagel API container (node API container)

Not implement
- I would colour code the first 4 lines of the .env file table that you strongly suggest that users set
-  In .template-env file have the first 4 lines be the settings you want people to always configure. Also for the following:
-  Don't make the template a '.' file. It's easy to miss
- change command: docker compose up -d to: sudo docker-compose up -d

@neurobagel/dev any notes / changes? If not, I'll create those issues and turn this into a tracking issue

**Comment by alyssadai** [comment]
Agree with your prioritization @surchs! Thanks :)

**Comment by surchs** [comment]
Removing this from the board, we'll implement the tracked issues individually and then close this guy here.

**Comment by surchs** [comment]
Closing this as completed, thank you again very much for all the feedback @thomasbeaudry!
